export const stepsDes = {
  Commit: '提交',
  Branch: '分支',
  Credentials: '凭证',
  Credential: '凭证',
  Normal: '通用',
  Artifacts: '制品',
  artifacts: '制品',
  remote: '仓库地址',
  branch: '分支',
  submitter: '审核者',
  SCM: '代码仓库',
  Review: '审核',
  expression: '表达式',
  abortPipeline: '检查结果是否影响后续任务',
  waitForQualityGate: '代码质量检查(SonarQube)',
  mail: '邮件',
  echo: '打印消息',
  withCredentials: '添加凭证',
  container: '指定容器',
  archiveArtifacts: '保存制品',
  input: '审核',
  timeout: '超时',
  Timeout: '超时',
  withSonarQubeEnv: 'Sonarqube 配置',
  sh: 'shell 脚本',
  credentialsId: '凭证 ID',
  name: '名称',
  value: '值',
  message: '消息',
  to: '至',
  cc: '抄送',
  subject: '主题',
}
